// Generated by scripts/gen-review-stats.mjs from reviews.ts — do not edit.
import type { PerfumeReviewStats } from "./reviews";

export const REVIEW_STATS: Record<string, PerfumeReviewStats> = {
  "calantha": {
    "count": 52,
    "averageRating": 4.92,
    "ratingBreakdown": {
      "1": 0,
      "2": 0,
      "3": 0,
      "4": 4,
      "5": 48
    }
  },
  "deep-crush": {
    "count": 54,
    "averageRating": 4.91,
    "ratingBreakdown": {
      "1": 0,
      "2": 0,
      "3": 0,
      "4": 5,
      "5": 49
    }
  },
  "herrlich": {
    "count": 46,
    "averageRating": 4.98,
    "ratingBreakdown": {
      "1": 0,
      "2": 0,
      "3": 0,
      "4": 1,
      "5": 45
    }
  },
  "midnight": {
    "count": 48,
    "averageRating": 4.96,
    "ratingBreakdown": {
      "1": 0,
      "2": 0,
      "3": 0,
      "4": 2,
      "5": 46
    }
  },
  "mirai": {
    "count": 50,
    "averageRating": 4.98,
    "ratingBreakdown": {
      "1": 0,
      "2": 0,
      "3": 0,
      "4": 1,
      "5": 49
    }
  },
  "0809": {
    "count": 58,
    "averageRating": 4.95,
    "ratingBreakdown": {
      "1": 0,
      "2": 0,
      "3": 0,
      "4": 3,
      "5": 55
    }
  },
  "personna": {
    "count": 44,
    "averageRating": 4.89,
    "ratingBreakdown": {
      "1": 0,
      "2": 0,
      "3": 0,
      "4": 5,
      "5": 39
    }
  },
  "purple-oud": {
    "count": 60,
    "averageRating": 4.9,
    "ratingBreakdown": {
      "1": 0,
      "2": 0,
      "3": 0,
      "4": 6,
      "5": 54
    }
  },
  "rich": {
    "count": 51,
    "averageRating": 4.96,
    "ratingBreakdown": {
      "1": 0,
      "2": 0,
      "3": 0,
      "4": 2,
      "5": 49
    }
  },
  "seductive": {
    "count": 59,
    "averageRating": 4.86,
    "ratingBreakdown": {
      "1": 0,
      "2": 0,
      "3": 0,
      "4": 8,
      "5": 51
    }
  },
  "white-oud": {
    "count": 55,
    "averageRating": 4.91,
    "ratingBreakdown": {
      "1": 0,
      "2": 0,
      "3": 0,
      "4": 5,
      "5": 50
    }
  },
  "zephyrine": {
    "count": 42,
    "averageRating": 4.81,
    "ratingBreakdown": {
      "1": 0,
      "2": 0,
      "3": 0,
      "4": 8,
      "5": 34
    }
  },
  "bijou": {
    "count": 45,
    "averageRating": 4.93,
    "ratingBreakdown": {
      "1": 0,
      "2": 0,
      "3": 0,
      "4": 3,
      "5": 42
    }
  },
  "dapper": {
    "count": 41,
    "averageRating": 4.98,
    "ratingBreakdown": {
      "1": 0,
      "2": 0,
      "3": 0,
      "4": 1,
      "5": 40
    }
  },
  "le-chocolat": {
    "count": 53,
    "averageRating": 4.89,
    "ratingBreakdown": {
      "1": 0,
      "2": 0,
      "3": 0,
      "4": 6,
      "5": 47
    }
  },
  "pc-leather": {
    "count": 47,
    "averageRating": 4.89,
    "ratingBreakdown": {
      "1": 0,
      "2": 0,
      "3": 0,
      "4": 5,
      "5": 42
    }
  },
  "quantillion": {
    "count": 39,
    "averageRating": 4.87,
    "ratingBreakdown": {
      "1": 0,
      "2": 0,
      "3": 0,
      "4": 5,
      "5": 34
    }
  },
  "reiz": {
    "count": 43,
    "averageRating": 4.91,
    "ratingBreakdown": {
      "1": 0,
      "2": 0,
      "3": 0,
      "4": 4,
      "5": 39
    }
  },
  "sent-aura": {
    "count": 38,
    "averageRating": 4.87,
    "ratingBreakdown": {
      "1": 0,
      "2": 0,
      "3": 0,
      "4": 5,
      "5": 33
    }
  },
  "vanaco": {
    "count": 40,
    "averageRating": 4.92,
    "ratingBreakdown": {
      "1": 0,
      "2": 0,
      "3": 0,
      "4": 3,
      "5": 37
    }
  },
  "woo-dy": {
    "count": 46,
    "averageRating": 4.89,
    "ratingBreakdown": {
      "1": 0,
      "2": 0,
      "3": 0,
      "4": 5,
      "5": 41
    }
  }
};

const NONE: PerfumeReviewStats = {
  count: 0,
  averageRating: 5.0,
  ratingBreakdown: { 5: 0, 4: 0, 3: 0, 2: 0, 1: 0 },
};

/** A perfume's review summary, without loading the reviews themselves. */
export const getReviewStats = (productId: string): PerfumeReviewStats =>
  REVIEW_STATS[productId] ?? NONE;
