name: Build & Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

concurrency:
  group: cloud-run-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-backend:
    name: Deploy Backend to Cloud Run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Build and Push Backend Container
        run: |
          gcloud auth configure-docker asia-south1-docker.pkg.dev --quiet
          docker build -t asia-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/ecommerce-backend-repo/ecommerce-backend:latest ./backend
          docker push asia-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/ecommerce-backend-repo/ecommerce-backend:latest

      - name: Deploy Backend to Cloud Run
        run: |
          gcloud run deploy ecommerce-backend \
            --image asia-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/ecommerce-backend-repo/ecommerce-backend:latest \
            --region asia-south1 \
            --min-instances=1 \
            --allow-unauthenticated \
            --port 8080 \
            --quiet

  deploy-frontend:
    name: Deploy Frontend to Cloud Run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Build and Push Frontend Container
        run: |
          gcloud auth configure-docker asia-south1-docker.pkg.dev --quiet
          docker build -t asia-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/ecommerce-frontend-repo/ecommerce-frontend:latest ./frontend
          docker push asia-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/ecommerce-frontend-repo/ecommerce-frontend:latest

      - name: Deploy Frontend to Cloud Run
        run: |
          gcloud run deploy ecommerce-frontend \
            --image asia-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/ecommerce-frontend-repo/ecommerce-frontend:latest \
            --region asia-south1 \
            --min-instances=1 \
            --allow-unauthenticated \
            --port 8080 \
            --quiet
